# Generated by Django 6.0.2 on 2026-02-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=155)),
                ('course_code', models.CharField(max_length=155)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
