# Generated by Django 6.0.1 on 2026-02-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.TextField()),
                ('enr_num', models.IntegerField()),
                ('course', models.TextField()),
                ('sem', models.IntegerField()),
                ('section', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enr_num', models.IntegerField()),
                ('stu_name', models.TextField()),
                ('father_name', models.TextField()),
                ('mother_name', models.TextField()),
                ('add', models.TextField()),
                ('ph_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
